// <auto-generated />
namespace ArtGallery2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ArtGallery2_202102171930 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArtGallery2_202102171930));
        
        string IMigrationMetadata.Id
        {
            get { return "202102180030500_ArtGallery2_202102171930"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
