// <auto-generated />
namespace ArtGallery2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ArtGallery2_202102091849 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArtGallery2_202102091849));
        
        string IMigrationMetadata.Id
        {
            get { return "202102092350019_ArtGallery2_202102091849"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
